# Generated by Django 2.2 on 2024-10-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
    ]
