# Generated by Django 2.2 on 2024-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20241020_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancustomer',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loancustomer',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
